runtime: python37
service: default

handlers:
  - url: /.*
    script: auto
env_variables:
  IS_APP_ENGINE: true
  CLOUDSQL_CONNECTION_NAME: frendsend:us-central1:cloudy-mysql
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: Swaps_07
  CLOUDSQL_DATABASE: main_db